#!/usr/bin/env python3
"""Compile a CEE project glossary into Vale substitution rules.

Usage:
    python3 glossary-to-vale.py <glossary.md> [output.yml]

Reads the markdown table format defined in references/dictionary.md and emits
one Vale `substitution` rule mapping every banned synonym to its approved
term. Writes to stdout when no output path is given.

Gloss-only entries (no banned synonyms) are skipped: they carry a stakeholder
translation, not a word ban, so there is nothing deterministic to enforce.

Vale is one backend. The glossary stays plain markdown so another checker can
be added without touching it.

Stdlib only. Exit codes: 0 = wrote rules, 1 = malformed input or no usable
rows.
"""

import re
import sys
from pathlib import Path

EXPECTED_HEADERS = ["term", "pos", "meaning", "banned synonyms", "stakeholder gloss"]
SEPARATOR_RE = re.compile(r"^\s*\|?[\s:|-]+\|[\s:|-]*$")


class GlossaryError(Exception):
    """A named failure. Malformed input never passes silently."""


def split_row(line):
    """Split one markdown table row into stripped cells."""
    line = line.strip()
    if line.startswith("|"):
        line = line[1:]
    if line.endswith("|"):
        line = line[:-1]
    return [cell.strip() for cell in line.split("|")]


def find_table(lines):
    """Return the index of the header row of the glossary table."""
    for i, line in enumerate(lines):
        if "|" not in line:
            continue
        cells = [c.lower() for c in split_row(line)]
        if cells[:2] == EXPECTED_HEADERS[:2]:
            return i
    raise GlossaryError(
        "no glossary table found: expected a header row starting "
        "'| Term | POS |' (see references/dictionary.md)"
    )


def parse(text, source="<glossary>"):
    """Parse glossary markdown into (term, [banned synonyms]) pairs."""
    lines = text.splitlines()
    start = find_table(lines)

    header = [c.lower() for c in split_row(lines[start])]
    if header != EXPECTED_HEADERS:
        raise GlossaryError(
            f"{source}: unexpected columns {header}; expected {EXPECTED_HEADERS}"
        )

    if start + 1 >= len(lines) or not SEPARATOR_RE.match(lines[start + 1]):
        raise GlossaryError(f"{source}: table header is not followed by a separator row")

    entries = []
    seen_terms = {}
    seen_synonyms = {}

    for offset, line in enumerate(lines[start + 2 :], start=start + 3):
        if not line.strip():
            break
        if "|" not in line:
            break

        cells = split_row(line)
        if len(cells) != len(EXPECTED_HEADERS):
            raise GlossaryError(
                f"{source}:{offset}: row has {len(cells)} cells, expected "
                f"{len(EXPECTED_HEADERS)}: {line.strip()!r}"
            )

        term, pos, meaning, banned, _gloss = cells

        if not term:
            raise GlossaryError(f"{source}:{offset}: row has an empty Term cell")
        if not pos:
            raise GlossaryError(f"{source}:{offset}: term {term!r} has no part of speech")
        if not meaning:
            raise GlossaryError(f"{source}:{offset}: term {term!r} has no meaning")

        key = term.lower()
        if key in seen_terms:
            raise GlossaryError(
                f"{source}:{offset}: term {term!r} is already defined at line "
                f"{seen_terms[key]}"
            )
        seen_terms[key] = offset

        synonyms = [s.strip() for s in banned.split(",") if s.strip()]
        for synonym in synonyms:
            if synonym.lower() == key:
                raise GlossaryError(
                    f"{source}:{offset}: term {term!r} bans itself as a synonym"
                )
            owner = seen_synonyms.get(synonym.lower())
            if owner and owner != term:
                raise GlossaryError(
                    f"{source}:{offset}: synonym {synonym!r} is banned by both "
                    f"{owner!r} and {term!r}; one synonym maps to one term"
                )
            seen_synonyms[synonym.lower()] = term

        if synonyms:
            entries.append((term, synonyms))

    if not seen_terms:
        raise GlossaryError(f"{source}: glossary table has no rows")

    return entries


def escape(value):
    """Quote a YAML scalar with double quotes."""
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def emit(entries, source):
    """Render Vale substitution rule YAML."""
    out = [
        "# Generated by scripts/glossary-to-vale.py — do not edit by hand.",
        f"# Source: {source}",
        "#",
        "# Enforces G-W1 (one term per concept) for project vocabulary.",
        "extends: substitution",
        "message: \"G-W1: use '%s' instead of '%s'\"",
        "level: warning",
        "ignorecase: true",
        "swap:",
    ]

    for term, synonyms in entries:
        for synonym in sorted(synonyms, key=str.lower):
            out.append(f"  {escape(synonym)}: {escape(term)}")

    return "\n".join(out) + "\n"


def main(argv):
    if not 2 <= len(argv) <= 3:
        print(__doc__.strip(), file=sys.stderr)
        return 1

    source = Path(argv[1])
    try:
        text = source.read_text(encoding="utf-8")
    except OSError as exc:
        print(f"error: cannot read {source}: {exc}", file=sys.stderr)
        return 1

    try:
        entries = parse(text, source=str(source))
    except GlossaryError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    if not entries:
        print(
            f"error: {source} has rows but no banned synonyms, so there is "
            "nothing to enforce deterministically. Add banned synonyms, or "
            "rely on review alone.",
            file=sys.stderr,
        )
        return 1

    yaml = emit(entries, source)

    if len(argv) == 3:
        target = Path(argv[2])
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(yaml, encoding="utf-8")
        count = sum(len(s) for _, s in entries)
        print(f"wrote {count} substitutions for {len(entries)} terms to {target}")
    else:
        sys.stdout.write(yaml)

    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
