/**
 * Regenerates references/index.md from the vendored corpus.
 *
 * The index exists because the corpus is ~620k tokens and must never be read whole. It is a grep
 * target: one row per sheet, carrying every keyword that should match it, so `rg` returns the
 * filename to open. Upstream's own Index.md omits 24 shipped sheets, which is why this reads the
 * directory rather than translating theirs.
 *
 * Usage:
 *   bun build-index.ts
 */

import { existsSync, readdirSync } from 'node:fs';
import { CORPUS_DIR, isRedirectStub, redirectTarget } from './sync-owasp';

export interface SheetEntry {
	file: string;
	title: string;
	topics: string[];
	stacks: string[];
}

export interface RedirectEntry {
	file: string;
	target: string;
}

/** Subheadings that appear on nearly every sheet and so discriminate nothing. */
const BOILERPLATE = new Set([
	'introduction',
	'overview',
	'references',
	'summary',
	'conclusion',
	'background',
	'related articles',
	'further reading',
	'authors and primary editors',
	'tools',
]);

/** Filename fragments that carry no search signal. */
const FILENAME_NOISE = new Set(['cheat', 'sheet', 'the', 'and', 'for', 'of', 'in', 'a', 'to']);

/**
 * Matched against filename + title only, not the body — a body match would tag the XSS sheet as
 * "java" for containing one Java snippet, which makes the stack column useless for narrowing.
 */
export const STACK_RULES: ReadonlyArray<readonly [string, RegExp]> = [
	['node', /node|npm|express|javascript|typescript|deno/i],
	['java', /\bjava\b|jaas|bean_?validation|spring/i],
	['dotnet', /dotnet|\.net|csharp/i],
	['python', /django|python|flask/i],
	['php', /\bphp\b|laravel|symfony/i],
	['ruby', /rails|ruby/i],
	['container', /docker|kubernetes|container/i],
	['cloud', /cloud|serverless|faas|microservice/i],
	['web', /xss|csrf|cors|html|css|browser|dom|clickjack|cookie|session|clientside/i],
	['api', /rest|graphql|grpc|web_?service|ajax|websocket|soap/i],
	['data', /sql|nosql|database|query|ldap|xml|deserial/i],
	['ai', /\bllm\b|ai_?agent|\brag\b|\bmcp\b|prompt|model_?ops/i],
	['mobile', /mobile|android|ios/i],
	['supply-chain', /ci_?cd|github_?actions|supply_?chain|sbom|dependency|npm|third_?party/i],
	['auth', /authentication|authorization|oauth|saml|jwt|password|session|mfa|multifactor|credential/i],
	['crypto', /crypto|tls|cipher|key_?management|pinning|transport_?layer|hsts/i],
];

export function stacksOf(haystack: string): string[] {
	const hits = STACK_RULES.filter(([, re]) => re.test(haystack)).map(([tag]) => tag);
	return hits.length > 0 ? [...new Set(hits)] : ['any'];
}

/** Words from the filename, so a sheet is always findable by the terms in its own name. */
function filenameTopics(file: string): string[] {
	return file
		.replace(/\.md$/, '')
		.split('_')
		.map((w) => w.toLowerCase())
		.filter((w) => w.length > 1 && !FILENAME_NOISE.has(w));
}

export function parseSheet(file: string, text: string): SheetEntry {
	const title = /^#\s+(.+)$/m.exec(text)?.[1]?.trim() ?? file.replace(/_/g, ' ').replace(/\.md$/, '');

	// Fenced code must go before the heading scan. `##` is also a comment marker in Makefiles,
	// C preprocessor listings, and ModSecurity rules, and the corpus has 37 such lines inside
	// fences — they parsed as headings and leaked code fragments into the shipped index.
	// validate_skill.ts:130 strips fences the same way for the same reason.
	const prose = text.replace(/```[\s\S]*?```/g, '');

	// Harvest `###` as well as `##`. Topical sections live at `##`, but the terms a reviewer
	// actually greps — Argon2id, bcrypt, scrypt, PBKDF2, IDOR — are all one level deeper, and
	// every one of them returned zero index rows when only `##` was scanned. IDOR is the worked
	// example in this skill's own findings.md. The `.slice(0, 24)` cap below bounds the growth.
	const headings = [...prose.matchAll(/^###?\s+(.+)$/gm)]
		.map((m) => (m[1] ?? '').trim().toLowerCase().replace(/[`*]/g, ''))
		.filter((h) => h.length > 2 && h.length < 60 && !BOILERPLATE.has(h));

	const topics = [...new Set([...filenameTopics(file), ...headings])]
		.filter((t) => t !== 'cheat' && t !== 'sheet')
		.slice(0, 24);

	return { file, title, topics, stacks: stacksOf(`${file} ${title}`) };
}

/** Pipes would break the markdown table; commas are the row's internal separator. */
const cell = (s: string): string => s.replace(/\|/g, '/');

export function renderIndex(sheets: SheetEntry[], redirects: RedirectEntry[], sha: string): string {
	const rows = sheets
		.map((s) => `| \`${s.file}\` | ${cell(s.title)} | ${cell(s.topics.join(', '))} | ${s.stacks.join(', ')} |`)
		.join('\n');

	const redirectRows = redirects
		.map((r) => `| \`${r.file}\` | \`${r.target}\` |`)
		.join('\n');

	return `# OWASP Cheat Sheet Index

Generated by \`scripts/build-index.ts\` from \`owasp/\` at commit ${sha}. Do not edit by hand —
the next sync overwrites it. The commit above must match \`owasp/SOURCE.json\`; a mismatch means
the corpus was synced without rebuilding this index, and its topics describe sheets that no
longer exist.

Contents:
- [How to use this file](#how-to-use-this-file)
- [Sheets](#sheets)
- [Redirects](#redirects)

## How to use this file

Do not read this file whole, and never read the corpus whole — it is roughly 620,000 tokens. Grep
for the topic or stack, then open only the sheets named in the matching rows:

    rg -i "sql|injection" references/index.md
    rg -i "\\| python" references/index.md

Each row carries every keyword that should match its sheet, so one grep is enough to choose.

## Sheets

${sheets.length} citable sheets.

| Sheet | Title | Topics | Stack |
|---|---|---|---|
${rows}

## Redirects

Deprecated stubs. They contain no guidance — cite the target instead.

| Deprecated | Use instead |
|---|---|
${redirectRows}
`;
}

async function main(): Promise<number> {
	const srcPath = `${CORPUS_DIR}SOURCE.json`;
	if (!existsSync(srcPath)) {
		console.error(
			`ERROR: ${srcPath} not found. Run scripts/sync-owasp.ts first — an index with no provenance cannot be checked against its corpus, which is the whole reason this stamp exists.`,
		);
		return 1;
	}
	const { sha } = (await Bun.file(srcPath).json()) as { sha?: string };
	// The cast is a claim, not a check. A SOURCE.json that exists but has no usable `sha` would
	// otherwise stamp the header "at commit undefined" and exit 0 with a success message — an
	// index with no provenance, which is the exact thing this stamp exists to prevent. Verified:
	// deleting the field produced that header and exit 0 before this guard was added.
	if (typeof sha !== 'string' || !/^[0-9a-f]{40}$/.test(sha)) {
		console.error(`ERROR: ${srcPath} has no usable 40-character sha (got ${JSON.stringify(sha)}). Re-run scripts/sync-owasp.ts.`);
		return 1;
	}

	const sheets: SheetEntry[] = [];
	const redirects: RedirectEntry[] = [];

	for (const file of readdirSync(CORPUS_DIR).filter((f) => f.endsWith('_Cheat_Sheet.md')).sort()) {
		const text = await Bun.file(`${CORPUS_DIR}${file}`).text();
		if (isRedirectStub(text)) {
			redirects.push({ file, target: redirectTarget(text) ?? '(unresolved)' });
			continue;
		}
		sheets.push(parseSheet(file, text));
	}

	const out = new URL('../references/index.md', import.meta.url).pathname;
	await Bun.write(out, renderIndex(sheets, redirects, sha));
	console.log(`indexed ${sheets.length} sheets and ${redirects.length} redirects`);
	return 0;
}

if (import.meta.main) process.exit(await main());
