import json
import subprocess
import unittest
from pathlib import Path

GUARD = Path(__file__).resolve().parents[2] / "hooks" / "scripts" / "godot-guard.sh"

CASES = [
    # (command, expected decision)
    # --- deny: unrepairable -------------------------------------------------
    ("mv scripts/player.gd entities/player.gd", "deny"),
    ("git mv src/enemy.gd actors/enemy.gd", "deny"),
    ("mv water.gdshader shaders/water.gdshader", "deny"),
    ("godot --headless --path . --convert-3to4", "deny"),
    # --- allow: the sidecar travels too ------------------------------------
    ("mv scripts/player.gd entities/player.gd && mv scripts/player.gd.uid entities/player.gd.uid", "allow"),
    ("mv scripts/ entities/", "allow"),
    ("git mv scripts entities", "allow"),
    # --- allow: uid lives inside the file -----------------------------------
    ("mv main.tscn scenes/main.tscn", "allow"),
    ("mv theme.tres ui/theme.tres", "allow"),
    # --- allow: regenerable -------------------------------------------------
    ("rm -rf .godot", "allow"),
    ("rm -rf .godot/imported", "allow"),
    # Spec 3.8: UIDs are path-derived, so deleting a sidecar in place
    # regenerates the identical UID. Denying these would be noise.
    ("rm scripts/player.gd.uid", "allow"),
    ("rm -f assets/hero.png.import", "allow"),
    ("rm assets/hero.png.import && godot --headless --import", "allow"),
    # --- ask: recoverable from git -----------------------------------------
    ("rm scripts/player.gd", "ask"),
    ("rm main.tscn", "ask"),
    ("rm project.godot", "ask"),
    ("rm export_presets.cfg", "ask"),
    # --- allow: ordinary work ----------------------------------------------
    ("godot --headless --path . --check-only --script main.gd", "allow"),
    ("ls scripts/", "allow"),
    ("cat scripts/player.gd", "allow"),
    ("grep -rn 'uid://' .", "allow"),
    ("godot --headless --path . --export-release macOS builds/game.dmg", "allow"),
    ("git status", "allow"),
]


def decide(command):
    payload = json.dumps({"tool_name": "Bash", "tool_input": {"command": command}})
    proc = subprocess.run(
        ["bash", str(GUARD)], input=payload, capture_output=True, text=True, timeout=10
    )
    out = proc.stdout.strip()
    if not out:
        return "allow"
    return json.loads(out)["hookSpecificOutput"]["permissionDecision"]


class TestGuard(unittest.TestCase):
    def test_decision_table(self):
        failures = []
        for command, expected in CASES:
            actual = decide(command)
            if actual != expected:
                failures.append(f"{command!r}: expected {expected}, got {actual}")
        self.assertEqual(failures, [], "\n".join(failures))

    def test_permits_godot_cache_removal(self):
        # A guard that fires on harmless operations gets disabled, and then it
        # protects nothing. .godot/ is regenerated by --import.
        self.assertEqual(decide("rm -rf .godot"), "allow")

    def test_deny_message_explains_the_fix(self):
        payload = json.dumps(
            {"tool_name": "Bash", "tool_input": {"command": "mv a.gd b/a.gd"}}
        )
        proc = subprocess.run(
            ["bash", str(GUARD)], input=payload, capture_output=True, text=True, timeout=10
        )
        reason = json.loads(proc.stdout)["hookSpecificOutput"]["permissionDecisionReason"]
        self.assertIn(".uid", reason)

    def test_non_bash_tools_are_ignored(self):
        payload = json.dumps({"tool_name": "Read", "tool_input": {"file_path": "a.gd"}})
        proc = subprocess.run(
            ["bash", str(GUARD)], input=payload, capture_output=True, text=True, timeout=10
        )
        self.assertEqual(proc.stdout.strip(), "")


if __name__ == "__main__":
    unittest.main()
